version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ticketrush-redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: ticketrush-api
    restart: always
    ports:
      - "3000:3000"
    env_file: 
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  worker-email:
    build: .
    container_name: ticketrush-worker-email
    restart: always
    command: ["node", "modules/jobs/workers/emailWorker.js"]
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  worker-seat-release:
    build: .
    container_name: ticketrush-worker-release
    restart: always
    command: ["node", "modules/jobs/workers/seatReleaseWorker.js"]
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
