version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ticketrush-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketrush
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ticketrush"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: ticketrush-redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: ticketrush-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ticketrush_uploads:/app/public/img
    env_file: 
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://user:password@postgres:5432/ticketrush
      - DIRECT_URL=postgresql://user:password@postgres:5432/ticketrush
    depends_on:
      - redis
      - postgres

  worker-email:
    build: .
    container_name: ticketrush-worker-email
    restart: always
    command: ["node", "modules/jobs/workers/emailWorker.js"]
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://user:password@postgres:5432/ticketrush
      - DIRECT_URL=postgresql://user:password@postgres:5432/ticketrush
    depends_on:
      - redis
      - postgres

  worker-seat-release:
    build: .
    container_name: ticketrush-worker-release
    restart: always
    command: ["node", "modules/jobs/workers/seatReleaseWorker.js"]
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://user:password@postgres:5432/ticketrush
      - DIRECT_URL=postgresql://user:password@postgres:5432/ticketrush
    depends_on:
      - redis
      - postgres

volumes:
  ticketrush_uploads:
